import { useCallback, MutableRefObject } from 'react';
import { FileText } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { COMPONENTS } from '@/components/ComponentRemoval';
import { SERVICES } from '@/components/ServicesManager';
import { toast } from 'sonner';
import type { WimFeatureExport } from '@/components/WimEditor';

interface MarkdownExportProps {
  exportCustomizations: MutableRefObject<() => { programs: string[]; tweaks: string[]; optimizations: string[] }>;
  exportDrivers: MutableRefObject<() => { name: string; path: string; type: string }[]>;
  exportUpdates: MutableRefObject<() => { kb: string; title: string; category: string; source: string; filePath?: string }[]>;
  exportServices: MutableRefObject<() => string[]>;
  exportComponents: MutableRefObject<() => string[]>;
  exportRegistry: MutableRefObject<() => { hive: string; keyPath: string; valueName: string; valueType: string; valueData: string }[]>;
  exportFeatures: MutableRefObject<() => WimFeatureExport[]>;
  isMounted: boolean;
}

const MarkdownExport = ({
  exportCustomizations,
  exportDrivers,
  exportUpdates,
  exportServices,
  exportComponents,
  exportRegistry,
  exportFeatures,
  isMounted,
}: MarkdownExportProps) => {
  const generate = useCallback(() => {
    const cust = exportCustomizations.current();
    const drivers = exportDrivers.current();
    const updates = exportUpdates.current();
    const services = exportServices.current();
    const components = exportComponents.current();
    const registry = exportRegistry.current();
    const features = exportFeatures.current();

    const date = new Date().toLocaleString();
    const lines: string[] = [
      '# ISO Forge — Build Report',
      '',
      `**Generated:** ${date}`,
      '',
      '---',
      '',
    ];

    // Customizations
    const allCust = [...cust.programs, ...cust.tweaks, ...cust.optimizations];
    if (allCust.length > 0) {
      lines.push('## Customizations', '');
      if (cust.programs.length > 0) {
        lines.push('### Programs', '');
        cust.programs.forEach(p => lines.push(`- ${p.replace(/-/g, ' ')}`));
        lines.push('');
      }
      if (cust.tweaks.length > 0) {
        lines.push('### Tweaks', '');
        cust.tweaks.forEach(t => lines.push(`- ${t.replace(/-/g, ' ')}`));
        lines.push('');
      }
      if (cust.optimizations.length > 0) {
        lines.push('### Optimizations', '');
        cust.optimizations.forEach(o => lines.push(`- ${o.replace(/-/g, ' ')}`));
        lines.push('');
      }
    }

    // Components removed
    if (components.length > 0) {
      lines.push('## Components Removed', '', '| Component | Package | Size |', '| --- | --- | --- |');
      components.forEach(id => {
        const c = COMPONENTS.find(x => x.id === id);
        lines.push(`| ${c?.name || id} | ${c?.packageName || '—'} | ${c?.size || '—'} |`);
      });
      lines.push('');
    }

    // Services disabled
    if (services.length > 0) {
      lines.push('## Services Disabled', '', '| Service | Display Name | Risk |', '| --- | --- | --- |');
      services.forEach(name => {
        const s = SERVICES.find(x => x.name === name);
        lines.push(`| ${name} | ${s?.displayName || '—'} | ${s?.risk || '—'} |`);
      });
      lines.push('');
    }

    // Registry
    if (registry.length > 0) {
      lines.push('## Registry Modifications', '', '| Hive | Key Path | Value | Type | Data |', '| --- | --- | --- | --- | --- |');
      registry.forEach(e => {
        lines.push(`| ${e.hive} | ${e.keyPath} | ${e.valueName} | ${e.valueType} | \`${e.valueData}\` |`);
      });
      lines.push('');
    }

    // Drivers
    if (drivers.length > 0) {
      lines.push('## Drivers Injected', '');
      drivers.forEach(d => lines.push(`- **${d.name}** — \`${d.path}\` (${d.type})`));
      lines.push('');
    }

    // Updates
    if (updates.length > 0) {
      lines.push('## Updates Slipstreamed', '', '| KB | Title | Category |', '| --- | --- | --- |');
      updates.forEach(u => lines.push(`| ${u.kb} | ${u.title} | ${u.category} |`));
      lines.push('');
    }

    // WIM Features
    const enabled = features.filter(f => f.enabled);
    if (enabled.length > 0) {
      lines.push('## WIM Features Enabled', '');
      enabled.forEach(f => lines.push(`- ${f.name}`));
      lines.push('');
    }

    lines.push('---', '', '*Report generated by ISO Forge v1.3.0*');

    const md = lines.join('\n');
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `iso-forge-report_${new Date().toISOString().slice(0, 10)}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('Markdown report exported');
  }, [exportCustomizations, exportDrivers, exportUpdates, exportServices, exportComponents, exportRegistry, exportFeatures]);

  return (
    <Button
      variant="outline"
      size="sm"
      className="h-8 text-xs font-mono gap-1.5"
      disabled={!isMounted}
      onClick={generate}
    >
      <FileText className="w-3.5 h-3.5" />
      Report
    </Button>
  );
};

export default MarkdownExport;
